services:


  snapbite-mongo:
    image: snapbite-mongo
    build: ../mongo
    container_name: snapbite-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      # 把 本机上的 mongo-data 文件夹映射为 Mongo 容器内的数据库目录。
      - ../mongo/mongo-data:/data/db
    networks:
      - snapbite-net


  snapbite-user-service:
    image: snapbite-user-service
    build: ../user-service
    container_name: snapbite-user-service
    ports:
      - "8081:8081"
    env_file:
      - /user-service/.env.dev-docker
    depends_on:
      - snapbite-mongo
    networks:
      - snapbite-net


  snapbite-restaurant-service:
    image: snapbite-restaurant-service
    build: ../restaurant-service
    container_name: snapbite-restaurant-service
    ports:
      - "8082:8082"
    env_file:
      - /restaurant-service/.env.dev-docker
    depends_on:
      - snapbite-mongo
    networks:
      - snapbite-net

  snapbite-cart-service:
    image: snapbite-cart-service
    build: ../cart-service
    container_name: snapbite-cart-service
    ports:
      - "8083:8083"
    env_file:
      - /cart-service/.env.dev-docker
    depends_on:
      - snapbite-mongo
      - snapbite-restaurant-service
      - snapbite-user-service
    networks:
      - snapbite-net
    environment:
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=DEBUG


  snapbite-order-service:
    image: snapbite-order-service
    build: ../order-service
    container_name: snapbite-order-service
    ports:
      - "8084:8084"
    env_file:
      - /order-service/.env.dev-docker
    depends_on:
      - snapbite-mongo
      - snapbite-cart-service
      - snapbite-user-service
    networks:
      - snapbite-net


  snapbite-nginx:
    image: snapbite-nginx
    build: ../nginx
    container_name: snapbite-nginx
    ports:
      - "80:80"  # 把宿主机的 80 映射给 nginx 容器
    depends_on:
      - snapbite-mongo
      - snapbite-user-service
      - snapbite-restaurant-service
      - snapbite-cart-service
      - snapbite-order-service
    networks:
      - snapbite-net



networks:
  snapbite-net:
    driver: bridge
