
services:
  jenkins:
    build:
      context: ./jenkins  # 你放 Dockerfile 的路径
    container_name: snapbite-jenkins
    ports:
      #  宿主机用 8090
      # 容器内部还是跑在 8080（Jenkins 默认端口）
      - "8090:8080"
    volumes:
      - ./data/jenkins_home:/var/jenkins_home              # ✅ 数据持久化
      - /var/run/docker.sock:/var/run/docker.sock   #  让 Jenkins 控制宿主机 Docker
    restart: unless-stopped



volumes:
  jenkins_home:

