name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'user-service/**'
      - 'cart-service/**'
      - 'order-service/**'
      - 'restaurant-service/**'
      - 'frontend/**'
      - 'docker/nginx/**'

jobs:
  build-user-service:
    name: Build User Service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: ./user-service
          platforms: linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/snapbite-user-service:latest

  build-cart-service:
    name: Build Cart Service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: ./cart-service
          platforms: linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/snapbite-cart-service:latest

  build-order-service:
    name: Build Order Service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: ./order-service
          platforms: linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/snapbite-order-service:latest

  build-restaurant-service:
    name: Build Restaurant Service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: ./restaurant-service
          platforms: linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/snapbite-restaurant-service:latest


  build-nginx:
    name: Build Nginx with Frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Nginx container
        uses: docker/build-push-action@v5
        with:
          context: ./docker/nginx
          platforms: linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/snapbite-nginx:latest
